spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 418032
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/innowise-microservices
      client:
        registration:
          keycloak:
            client-id: userservice
            client-secret: w6u81iqv8zBjugCLMQkySY8wNQGgow3i
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/innowise-microservices
            user-name-attribute: preferred_username

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true